# Maintainer: SudoMaker
# Hermes - Game streaming server with virtual display support

pkgname=hermes-streaming
pkgver=0.5.1
pkgrel=1
pkgdesc="Self-hosted game streaming server with virtual display support"
arch=('x86_64')
url='https://github.com/MrOz59/Hermes'
license=('GPL-3.0-only')
install=hermes.install

depends=(
  'avahi'
  'curl'
  'libcap'
  'libdrm'
  'libevdev'
  'libpulse'
  'libva'
  'libx11'
  'libxcb'
  'libxfixes'
  'libxrandr'
  'libxtst'
  'miniupnpc'
  'numactl'
  'openssl'
  'opus'
  'qt6-base'
  'qt6-svg'
  'udev'
)

makedepends=(
  'base-devel'
  'cmake'
  'git'
  'git-lfs'
  'nodejs'
  'npm'
)

optdepends=(
  'cuda: NVIDIA GPU encoding support'
  'evdi: Virtual display support for streaming to headless clients (AUR)'
  'gamescope: application-only experimental independent client sessions'
  'hermes-kms: zero-copy Hermes virtual displays and independent DRM devices'
  'kscreen: KDE Plasma Wayland virtual-display activation'
  'libva-mesa-driver: AMD GPU encoding support'
  'seatd: private seat brokers for experimental independent client sessions'
  'weston: experimental independent desktop client sessions'
  'wl-clipboard: Hermes text clipboard synchronization on Wayland'
  'xclip: Hermes text clipboard synchronization on X11'
)

# The Arch package was originally published as `hermes`, but that name belongs
# to an unrelated AUR PAM authentication project. Prevent both packages from
# owning the same files, while automatically replacing only the old Hermes
# streaming packages whose versions were below 0.5.0.
conflicts=('hermes')
replaces=('hermes<0.5.0')

# Hermes installs under its own /usr/bin/hermes and /usr/share/hermes paths and
# ships hermes.service, so it can be installed side by side with the apollo (AUR)
# and sunshine packages — useful while the project is experimental. No provides
# or conflicts are declared for those packages; the binaries and unit names are
# all distinct.

# Keep the separate hermes-streaming-debug package. The main binary is still
# stripped, so nothing about the shipped package changes; what changes is that
# the symbols exist somewhere. Without them a user's crash report is a list of
# raw offsets into a stripped binary, which is exactly where the first two
# SIGSEGV reports stopped: the stack was there, and nothing could be said about
# what was on it. A debug package the reporter can install alongside turns
# `coredumpctl gdb` into an answer.
#
# Nothing is emitted unless the build environment asks for it: this relies on
# `debug` being in makepkg.conf's OPTIONS, which the CI container has and a
# plain local `makepkg` usually does not.

source=()
sha256sums=()

prepare() {
    cd "${startdir}"
    # A source checkout already containing the submodules needs no mutation
    # of .git metadata (for example, when building in a restricted sandbox).
    if [[ ! -d third-party/moonlight-common-c/enet ]]; then
      git submodule update --init --recursive
    fi
    if command -v git-lfs >/dev/null 2>&1; then
      git lfs pull
    fi
}

build() {
    cd "${startdir}"
    # Nightly CI stamps the short commit into pkgver (0.5.1+abc1234) and passes
    # the matching BUILD_VERSION, so the binary reports the commit it was built
    # from. A plain local `makepkg` inherits neither and falls back to pkgver.
    export BRANCH="${BRANCH:-local}"
    export BUILD_VERSION="${BUILD_VERSION:-${pkgver}}"
    export COMMIT="${COMMIT:-$(git rev-parse HEAD)}"

    # CUDA is required so the package ships NVIDIA NVENC hardware encoding. The
    # build fails if the CUDA toolkit is missing (CUDA_FAIL_ON_MISSING defaults
    # to ON) — install the `cuda` package (a makedepend) before building.
    cmake -S . -B build \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DSUNSHINE_ENABLE_CUDA=OFF \
      -DCUDA_FAIL_ON_MISSING=OFF \
      -DSUNSHINE_EXECUTABLE_PATH=/usr/bin/hermes \
      -DSUNSHINE_ASSETS_DIR=share/hermes
    cmake --build build
}

package() {
    cd "${startdir}"
    DESTDIR="${pkgdir}" cmake --install build

    rm "${pkgdir}/usr/bin/sunshine"
    mv "${pkgdir}/usr/bin/sunshine-"* "${pkgdir}/usr/bin/hermes"

    # The systemd unit generated by CMake is named sunshine.service; rename it
    # to hermes.service so it does not collide with an apollo/sunshine install.
    if [[ -f "${pkgdir}/usr/lib/systemd/user/sunshine.service" ]]; then
      mv "${pkgdir}/usr/lib/systemd/user/sunshine.service" \
         "${pkgdir}/usr/lib/systemd/user/hermes.service"
    fi
}
